<a href="https://colab.research.google.com/github/Nagayapallishaheen-333/deeplearning-213ECE3317/blob/main/odds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# date is
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
odds = tf.constant([1, 3, 5, 7, 9, 11], dtype=tf.int32)
print("odds:", odds)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_odds = tf.add(odds, ones)
print("just_beyond_odds:", just_beyond_odds)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
odds_doubled = odds * twos
print("odds_doubled:", odds_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
odds: tf.Tensor([ 1  3  5  7  9 11], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_odds: tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
odds_doubled: tf.Tensor([ 2  6 10 14 18 22], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
